version: "3.9"

services:
  cuda-dev:
    # 使用 build 指令通过 Dockerfile 构建镜像
    image: cuda-cpp-build:v1.0.0
    build: .
    container_name: cuda_cpp_build
    # 使用宿主机网络
    network_mode: host
    volumes:
      - ./:/workspace/Embedding_app
    working_dir: /workspace/Embedding_app
    tty: true
    stdin_open: true
    command: bash
    # 设置 runtime 为 nvidia
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]