name: Docker CI/CD

# 触发条件：推送到main分支，或手动触发
on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 步骤2：设置Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤3：登录到Docker镜像仓库
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 步骤4：构建并推送Docker镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fastembed-server:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fastembed-server:latest
          build-args: |
            USE_CUDA=ON
            USE_SERVER=ON